import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
page.on('console', msg => console.log('CONSOLE:', msg.type(), msg.text()));
page.on('pageerror', err => console.log('PAGE_ERROR:', err.message));
await page.goto('https://ai-wego.top/admin/listening-speaking', { waitUntil: 'networkidle', timeout: 30000 });
await page.waitForTimeout(3000);
await page.screenshot({ path: 'admin_screenshot.png', fullPage: true });
const html = await page.content();
console.log('--- HTML SNIPPET ---');
console.log(html.substring(0, 3000));
await browser.close();
