const fs = require('fs')
const path = require('path')

const WORD_DIR = path.join(__dirname, '..', '..', 'word')
const OUT = path.join(__dirname, '..', 'src', 'data', 'wordData.ts')

const FILES = [
  { file: '七上词汇.txt', gradeKey: 7, label: '七年级上册' },
  { file: '七下词汇.txt', gradeKey: 8, label: '七年级下册' },
  { file: '八上词汇.txt', gradeKey: 9, label: '八年级上册' },
  { file: '八下词汇.txt', gradeKey: 10, label: '八年级下册' },
]

const POS_RE = /^(n|v|adj|adv|pron|prep|conj|interj|num|art|aux|modal)\./

function stripLeadingPhon(line) {
  return line.replace(/^(\s*\/[^/]+\/\s*)+/, '').trim()
}

function stripPhonFromWord(word) {
  // remove phonetics glued into word like "Beijing roast /rəʊst/ duck" or "William /ˈwɪljəm/ Shakespeare"
  let w = word
  // pattern: /.../ where ... is a phonetic token (no spaces, or short parenthesized suffix like (r))
  w = w.replace(/\/[^/\s]+(?:\s+[^/\s]+)*\//g, ' ').trim()
  return w.replace(/\s+/g, ' ').trim()
}

function parseBare(body) {
  const after = body
  const wm = after.match(/^([A-Za-z][A-Za-z0-9'’\s.,()&\-\/]*?)(?:\s+(\/[^/]+\/[^/]*))?(?=\s+(?:[\u4e00-\u9fff]|(?:n|v|adj|adv|pron|prep|conj|interj|num|art|aux|modal)\.))/)
  if (!wm) {
    if (POS_RE.test(after)) return { type: 'cont', meaning: after }
    return null
  }
  const word = stripPhonFromWord(wm[1].trim())
  let rest = after.slice(wm[1].length).trim()
  rest = stripLeadingPhon(rest).trim()
  if (word && rest) return { type: 'entry', word, meaning: rest }
  return null
}

function parseLine(line) {
  const raw = line.trim()
  if (!raw) return null
  if (/^#+/.test(raw) && !/^-#/.test(raw)) return { type: 'unit', value: raw.replace(/^#+\s*/, '').replace(/\*\*/g, '').trim() }
  if (/^(Words|在英式|七上|七下|八上|八下|---|以下|（注)/.test(raw)) return null
  if (raw.includes('（单词未显示完整')) return null
  let tm = raw.match(/^\|\s*\d+\s*\|([^|]+)\|([^|]+)\|([^|]*)\|([^|]+)\|?/)
  if (tm) {
    const word = tm[1].trim()
    const pos = tm[3].trim()
    const meaning = tm[4].trim()
    if (word) return { type: 'entry', word, meaning: pos ? `${pos} ${meaning}`.trim() : meaning }
    return null
  }
  let lm = raw.match(/^-\s*\*\*([^*]+)\*\*\s*(.*?)\s*p\.\s*\d+\s*$/)
  if (lm) {
    const word = stripPhonFromWord(lm[1].trim())
    const rest = stripLeadingPhon(lm[2]).trim()
    if (word && rest) return { type: 'entry', word, meaning: rest }
    return null
  }
  if (/p\.\s*\d+/.test(raw)) return parseBare(raw.replace(/\s*p\.\s*\d+\s*$/, '').trim())
  if (/^[A-Za-z]/.test(raw) || POS_RE.test(raw)) return parseBare(raw)
  return null
}

// parse
const all = []
for (const cfg of FILES) {
  const txt = fs.readFileSync(path.join(WORD_DIR, cfg.file), 'utf8')
  const grade = cfg.gradeKey
  let curUnitName = ''
  let lastEntry = null
  for (const raw of txt.split('\n')) {
    const res = parseLine(raw)
    if (!res) continue
    if (res.type === 'unit') { curUnitName = res.value; continue }
    if (res.type === 'entry') {
      const word = stripPhonFromWord(res.word)
      res.grade = grade
      res.unitName = curUnitName
      all.push(res)
      lastEntry = res
      continue
    }
    if (res.type === 'cont') {
      if (lastEntry) lastEntry.meaning = lastEntry.meaning ? lastEntry.meaning + '；' + res.meaning : res.meaning
      continue
    }
  }
  console.log(cfg.file, '->', all.filter(e => e.grade === grade).length, 'entries')
}

// dedupe by (grade, word)
const seen = new Set()
const uniq = []
for (const e of all) {
  const k = e.grade + '|' + e.word.toLowerCase()
  if (seen.has(k)) continue
  seen.add(k)
  uniq.push(e)
}
console.log('after dedupe:', uniq.length)

// build units per grade
const unitsByGrade = {}
const unitIndexByGrade = {}
for (const e of uniq) {
  if (!unitsByGrade[e.grade]) unitsByGrade[e.grade] = []
  const u = e.unitName || ''
  if (!unitsByGrade[e.grade].includes(u)) unitsByGrade[e.grade].push(u)
}
for (const g of Object.keys(unitsByGrade)) {
  unitIndexByGrade[g] = {}
  unitsByGrade[g].forEach((u, i) => { unitIndexByGrade[g][u] = i })
}

// serialize
const gradeConfigLines = []
for (const cfg of FILES) {
  const g = cfg.gradeKey
  const units = unitsByGrade[g] || []
  const unitStrs = units.map(u => `"${u.replace(/"/g, '\\"')}"`)
  gradeConfigLines.push(`  ${g}: { label: '${cfg.label}', units: [${unitStrs.join(', ')}] },`)
}

const dataLines = []
for (const cfg of FILES) {
  const g = cfg.gradeKey
  dataLines.push(`  ${g}: [`)
  for (const e of uniq.filter(x => x.grade === g)) {
    const unitIdx = unitIndexByGrade[g][e.unitName] ?? 0
    const phonetic = ''
    dataLines.push(`  { "word": ${JSON.stringify(e.word)}, "phonetic": "", "meaning": ${JSON.stringify(e.meaning)}, "unit": ${unitIdx} },`)
  }
  dataLines.push(`  ],`)
}

const out = `// Auto-generated by scripts/parse-vocab.mjs from D:/ai-wego/word/*.txt
export interface Word {
  word: string;
  phonetic: string;
  meaning: string;
  unit: number;
}

export interface GradeConfig {
  label: string;
  units: string[];
}

export const GRADE_CONFIG: Record<number, GradeConfig> = {
${gradeConfigLines.join('\n')}
};

export const WORD_DATA: Record<number, Word[]> = {
${dataLines.join('\n')}
};
`
fs.writeFileSync(OUT, out, 'utf8')
console.log('written', OUT, '-', uniq.length, 'entries')

// verification
const badCJK = uniq.filter(e => /[\u4e00-\u9fff]/.test(e.word))
const badPhon = uniq.filter(e => e.word.includes('/'))
const badEmpty = uniq.filter(e => !e.meaning || !e.word)
console.log('verify - CJK in word:', badCJK.length, '| slash in word:', badPhon.length, '| empty fields:', badEmpty.length)
