export const PROVERBS = [
  { text: '💬 Where there is a will, there is a way. — 有志者事竟成', color: '#fbbf24' },
  { text: '💬 No pains, no gains. — 没有付出就没有收获', color: '#fbbf24' },
  { text: '💬 Constant dripping wears away the stone. — 滴水穿石', color: '#fbbf24' },
  { text: '💬 Reading to the mind while exercise to the body. — 读书健脑，运动健身', color: '#34d399' },
  { text: '💬 God helps those who help themselves. — 自助者天助', color: '#34d399' },
  { text: '💬 More haste, less speed. — 欲速则不达', color: '#f472b6' },
  { text: '💬 Well begun is half done. — 好的开端是成功的一半', color: '#60a5fa' },
  { text: '💬 Rome was not built in a day. — 伟业非一日之功', color: '#60a5fa' },
  { text: '💬 A bold attempt is half success. — 勇敢的尝试是成功的一半', color: '#a78bfa' },
  { text: '💬 Every little helps. — 积少成多', color: '#34d399' },
  { text: '💬 All things are difficult before they are easy. — 凡事必先难后易', color: '#fb923c' },
  { text: '💬 Nothing is impossible to a willing heart. — 心之所愿，无事不成', color: '#f472b6' },
  { text: '💬 Great hopes make great man. — 伟大的抱负造就伟大的人物', color: '#a78bfa' },
  { text: '💬 Industry is the parent of success. — 勤奋是成功之母', color: '#60a5fa' },
  { text: '💬 It is never too old to learn. — 活到老，学到老', color: '#34d399' },
  { text: '💬 A man becomes learned by asking questions. — 不耻下问才能有学问', color: '#fb923c' },
  { text: '💬 Knowledge starts with practice. — 实践出真知', color: '#fbbf24' },
  { text: '💬 Books and friends should be few but good. — 读书如交友，应求少而精', color: '#a78bfa' },
  { text: '💬 Practice makes perfect. — 熟能生巧', color: '#f472b6' },
  { text: '💬 Don\'t put off till tomorrow what should be done today. — 今日事，今日毕', color: '#60a5fa' },
  { text: '💬 Time and tide wait for no man. — 时不我待', color: '#fbbf24' },
  { text: '💬 Lost time is never found again. — 岁月既往，一去不回', color: '#fb923c' },
  { text: '💬 Time flies. — 光阴似箭', color: '#34d399' },
  { text: '💬 Every man is the architect of his own fortune. — 自己的命运自己掌握', color: '#a78bfa' },
  { text: '💬 Haste makes waste. — 忙中出错', color: '#f472b6' },
  { text: '💬 Look before you leap. — 三思而后行', color: '#60a5fa' },
  { text: '💬 He who laughs last laughs best. — 谁笑到最后，谁笑得最好', color: '#fbbf24' },
  { text: '💬 All roads lead to Rome. — 条条大路通罗马', color: '#34d399' },
  { text: '💬 Slow and steady wins the race. — 稳扎稳打无往而不胜', color: '#fb923c' },
  { text: '💬 The early bird catches the worm. — 早起的鸟儿有虫吃', color: '#a78bfa' },
  { text: '💬 It\'s never too late to mend. — 亡羊补牢，犹未为晚', color: '#f472b6' },
  { text: '💬 One is never too old to learn. — 活到老，学到老', color: '#60a5fa' },
  { text: '💬 A good book is a good friend. — 好书如挚友', color: '#34d399' },
  { text: '💬 When in Rome, do as Romans do. — 入乡随俗', color: '#fbbf24' },
  { text: '💬 The best preparation for tomorrow is doing your best today. — 对明天最好的准备就是今天做到最好', color: '#a78bfa' },
  { text: '💬 A good beginning makes a good ending. — 善始善终', color: '#fb923c' },
  { text: '💬 You can\'t judge a book by its cover. — 不能以貌取人', color: '#f472b6' },
  { text: '💬 Don\'t count your chickens before they are hatched. — 不要过早乐观', color: '#60a5fa' },
  { text: '💬 Strike while the iron is hot. — 趁热打铁', color: '#34d399' },
  { text: '💬 Two heads are better than one. — 三个臭皮匠，顶个诸葛亮', color: '#fbbf24' },
  { text: '💬 Nothing ventured, nothing gained. — 不入虎穴，焉得虎子', color: '#a78bfa' },
  { text: '💬 Hope for the best, but prepare for the worst. — 抱最好的愿望，做最坏的打算', color: '#fb923c' },
  { text: '💬 A fall into the pit, a gain in your wit. — 吃一堑，长一智', color: '#f472b6' },
  { text: '💬 Experience is the mother of wisdom. — 经验是智慧之母', color: '#60a5fa' },
  { text: '💬 East or west, home is best. — 金窝银窝不如自己的狗窝', color: '#34d399' },
  { text: '💬 There is no royal road to learning. — 学无坦途', color: '#fbbf24' },
  { text: '💬 If you want knowledge, you must toil for it. — 若要求知，必须刻苦', color: '#a78bfa' },
  { text: '💬 A little knowledge is a dangerous thing. — 一知半解，自欺欺人', color: '#fb923c' },
  { text: '💬 A man cannot spin and reel at the same time. — 一心不能二用', color: '#f472b6' },
  { text: '💬 Adversity leads to prosperity. — 穷则思变', color: '#60a5fa' },
  { text: '💬 All work and no play makes Jack a dull boy. — 只工作不玩耍，聪明孩子也变傻', color: '#34d399' },
  { text: '💬 Early to bed and early to rise makes a man healthy, wealthy and wise. — 早睡早起使人健康、富有和聪明', color: '#fbbf24' },
  { text: '💬 A good medicine tastes bitter. — 良药苦口', color: '#a78bfa' },
  { text: '💬 It\'s no use crying over spilt milk. — 覆水难收', color: '#fb923c' },
  { text: '💬 Prevention is better than cure. — 预防胜于治疗', color: '#f472b6' },
  { text: '💬 A friend in need is a friend indeed. — 患难见真情', color: '#60a5fa' },
  { text: '💬 Many hands make light work. — 众人拾柴火焰高', color: '#34d399' },
  { text: '💬 A single flower does not make a spring. — 一花独放不是春，百花齐放春满园', color: '#fbbf24' },
  { text: '💬 Fire and water have no mercy. — 水火无情', color: '#a78bfa' },
  { text: '💬 Truth is the daughter of time. — 时间见真理', color: '#fb923c' },
  { text: '💬 Patience is a virtue. — 耐心是一种美德', color: '#f472b6' },
  { text: '💬 Failure is the mother of success. — 失败是成功之母', color: '#60a5fa' },
  { text: '💬 Where there is life, there is hope. — 有生命就有希望', color: '#34d399' },
  { text: '💬 A good name is better than riches. — 美名胜过财富', color: '#fbbf24' },
  { text: '💬 A snow year, a rich year. — 瑞雪兆丰年', color: '#a78bfa' },
  { text: '💬 First things first. — 凡事有轻重缓急', color: '#fb923c' },
  { text: '💬 Do as you would be done by. — 己所不欲，勿施于人', color: '#f472b6' },
  { text: '💬 A stitch in time saves nine. — 小洞不补，大洞吃苦', color: '#60a5fa' },
  { text: '💬 He that climbs high falls heavily. — 爬得越高，摔得越重', color: '#34d399' },
  { text: '💬 A watched pot never boils. — 心急水不开', color: '#fbbf24' },
  { text: '💬 The pen is mightier than the sword. — 笔比剑更有力', color: '#a78bfa' },
  { text: '💬 Kill two birds with one stone. — 一箭双雕', color: '#fb923c' },
  { text: '💬 Success belongs to the persevering. — 坚持就是胜利', color: '#f472b6' },
  { text: '💬 One false step will make a great difference. — 失之毫厘，谬之千里', color: '#60a5fa' },
  { text: '💬 Easier said than done. — 说起来容易做起来难', color: '#34d399' },
  { text: '💬 Like father, like son. — 有其父必有其子', color: '#fbbf24' },
  { text: '💬 Great minds think alike. — 英雄所见略同', color: '#a78bfa' },
  { text: '💬 Every dog has its day. — 人人都有得意的时候', color: '#fb923c' },
  { text: '💬 A miss is as good as a mile. — 失之毫厘，差之千里', color: '#f472b6' },
  { text: '💬 A man can do no more than he can. — 凡事都应量力而行', color: '#60a5fa' },
  { text: '💬 Out of sight, out of mind. — 眼不见，心不烦', color: '#34d399' },
  { text: '💬 A cat may look at a king. — 人人平等', color: '#fbbf24' },
  { text: '💬 Money isn\'t everything. — 金钱不是万能的', color: '#a78bfa' },
  { text: '💬 The grass is always greener on the other side. — 这山望着那山高', color: '#fb923c' },
  { text: '💬 Walls have ears. — 隔墙有耳', color: '#f472b6' },
  { text: '💬 No news is good news. — 没有消息就是好消息', color: '#60a5fa' },
  { text: '💬 Better late than never. — 迟做总比不做好', color: '#34d399' },
  { text: '💬 Bad news has wings. — 好事不出门，坏事传千里', color: '#fbbf24' },
  { text: '💬 Birds of a feather flock together. — 物以类聚，人以群分', color: '#a78bfa' },
  { text: '💬 Keep good men company and you shall be of the number. — 近朱者赤，近墨者黑', color: '#fb923c' },
  { text: '💬 An apple a day keeps the doctor away. — 一天一个苹果，医生远离我', color: '#f472b6' },
  { text: '💬 Don\'t put all your eggs in one basket. — 不要孤注一掷', color: '#60a5fa' },
  { text: '💬 Every minute counts. — 分秒必争', color: '#34d399' },
  { text: '💬 A chain is no stronger than its weakest link. — 链条的坚固程度取决于它最薄弱的环节', color: '#fbbf24' },
  { text: '💬 All that glitters is not gold. — 闪光的不一定都是金子', color: '#a78bfa' },
  { text: '💬 You can\'t make an omelet without breaking eggs. — 有得必有失', color: '#fb923c' },
  { text: '💬 Health is happiness. — 健康就是幸福', color: '#f472b6' },
  { text: '💬 Man proposes, God disposes. — 谋事在人，成事在天', color: '#60a5fa' },
  { text: '💬 Facts speak louder than words. — 事实胜于雄辩', color: '#34d399' },
  { text: '💬 A sound mind in a sound body. — 健全的精神寓于健康的身体', color: '#fbbf24' },
  { text: '⭐ As the saying goes, "A good beginning is half the battle". — 良好的开端是成功的一半', color: '#a78bfa' },
  { text: '⭐ Francis Bacon once said, "Knowledge is power." — 知识就是力量', color: '#fb923c' },
  { text: '⭐ As we all know, books are the ladder of human progress. — 书籍是人类进步的阶梯', color: '#f472b6' },
  { text: '⭐ As a famous saying goes, "A friend is a present you give yourself." — 朋友是你给自己的礼物', color: '#60a5fa' },
  { text: '⭐ In a word, success is important, and so is failure, because it\'s the mother of success. — 成功和失败都重要，失败是成功之母', color: '#34d399' },
  { text: '⭐ It helps me understand the proverb, "Practice makes perfect." — 熟能生巧', color: '#fbbf24' },
  { text: '⭐ Above all, diligence is the mother of success. — 勤奋是成功之母', color: '#a78bfa' },
  { text: '⭐ Mother told me that where there is a will, there is a way. — 有志者事竟成', color: '#fb923c' },
  { text: '⭐ Some old people say, "The happiness will come when the pain leaves." — 苦尽甘来', color: '#f472b6' },
  { text: '⭐ If you "Do as the Romans do when in Rome", you\'ll enjoy more of your stay here. — 入乡随俗', color: '#60a5fa' },
]
